export const SET_THEME = 'SET_THEME';
export const SET_CATEGORY = 'SET_CATEGORY';
export const ANIMATE_PROJECTS_EXIT = 'ANIMATE_PROJECTS_EXIT';
export const ANIMATE_PROJECT_ENTER = 'ANIMATE_PROJECT_ENTER';